### ISSUE TITLE
User Story:  As a site admin I can create, read, update and delete articles so that I have a basic site

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#10]
EPIC:  Build MVP

As a **site admin* I can *create, read, update and delete articles** so that **the basic site engine is working**

### Assumptions:
* Starting from scratch

### Acceptance Criteria
* Basic site is created with Django project and first Django app
* Site structure is created (articles page with navbar, header, footer,)
* Elephant SQL database is setup 
*  Admin user has ability create read update delete articles

### Tasks

- [x] Task1 [Create site skeleton Issue #11](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/issues/11)
- [x] Task2 [Build database structure Issue #12](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/issues/12)
- [x] Task3 Create superuser profile
- [x] Task4 Install summernote
- [x] Task5 Add filters to admin views

**Comment by DeeMcCart** [comment]
Done 23/10/23:  Basic site (local version) is now working 


![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/0713a804-c687-4a37-8b76-2ae0bfe17f4d)



![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/f7151545-d51f-49ec-90b4-9514ff531631)
