### ISSUE TITLE
Task:  Create site skeleton

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#11]
EPIC:  Build MVP

Task:  Create site skeleton

### Assumptions:
* Starting from scratch

### Acceptance Criteria
* Basic site is created with Django project and first Django app
* Elephant SQL database is setup and linked
* Cloudinary is linked 
* Site is deployed successfully to Heroku
*
### Tasks

- [x] Task1 Cretae Django Project and App
- [x] Task2 Create an Elephant SQL external database
- [x] Task3 Create the heroku App & attach the database to it
- [x] Task4 Prepare env.py and settings.py files
- [x] Task5 Add Cloudinary links for image storage
- [x] Task6 Create a procfile
- [x] Taks7 Deploy
- [x] Task8 Test deploy,et

**Comment by DeeMcCart** [comment]
Done 22/10/23
Local site https://8000-deemccart-cipp4financia-vv93ot4q6wj.ws-eu105.gitpod.io/ gives 'the install worked successfully'
Heroku site https://financial-planner-6a030328a9ac.herokuapp.com/ gives 'the install worked successfully'
In each site I can navigate to the admin page and it offers me a login screen
