### ISSUE TITLE
Task:  Build initial database structure

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#12]
EPIC:  MVP

### Assumptions:
* Site Skeleton has been setup and first Heroku deployment created

### Acceptance Criteria
*  Data models are created  for articles, user_actions, themes

### Tasks

- [x] Task1 Create data model for Article in models.py
- [ ] Task2 Create data model for Themes in models.py
- [x] Task3 Create data model for Comments in models.py
- [x] Task4 Create data model for Action in models.py
- [ ] Task5 Create data model for User in models.py
- [ ] Task6 Create data model for User_Actions in models.py
- [ ] Task7 Work out how to represent favourite/ bookmarks
(see comments below as some of these tasks have been moved to Release1 Issue #30 and Release2 Issue #31 functionality

**Comment by Blackmercii2** [comment]
Hi DeeMc just came across this project and i'll love what you are working on and will love to contribute. is there a Discord link or how can i actively contribute to this project?

**Comment by DeeMcCart** [comment]
22.10.23 Created data models for Article, Comment, Action..... not sure if Comments will be needed.
23.10.23 Observed that owner of content is showing as email address (rather than username) of admin, will check models again to see if this is something wrong in setup

**Comment by DeeMcCart** [comment]
30/10/23 (Sprint 5 retrospective) this issue was worked on during sprint 5, so MVP items are completed. Moving back to 'to do' for sprint 6 as need to address data structures/ models needed for Release 1 (personalised Financial Planner with ability to track actions and bookmarks etc at the specific user profile level for registered users). Updated story points as 6 (remaining); this issue hadn't previously been assigned SPs.

**Comment by DeeMcCart** [comment]
01/11/23 Editing the scope of this Task to separate out MVP from Release1 jobs.   The items marked complete are MVP database structure items and are completed and tested.  The following items will be moved into a separate user story/task for Release 1 as they refer to additional functionality:
**Release 1: Personal Financial Planner**
- [ ] Task5 Create data model for User in models.py
- [ ] Task6 Create data model for User_Actions in models.py
- [ ] Task7 Work out how to represent favourite/ bookmarks
**Release 2: Themes/ Lifestage Planner**
- [ ] Task2 Create data model for Themes in models.py
