### ISSUE TITLE
User Story:  Show list of articles, including pagination after 6 articles

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#13]
EPIC:  **MVP**

As a **Site User** I can **view a paginated list of articles** so that **I can select one to read**

### Assumptions:
Admin profile creates the posts

### Acceptance Criteria
* User (not signed in) can see a list of published articles on the site homepage
* Articles are paginated with max 6(?) per page arranged in 3-column layout on desktop/laptop screen
 
### Tasks  (Model - View - Templates)
**Model** : already done
**View:** : 
- [x] Task1 In views.py, create class ArticleList as a listview with pagination 
**Templates:**
- [x] Task2 Create a templates folder (if doesn't already exist)
- [x] Task3 Populate a styles.css file into templates folder
- [x] Task4 Add base.html into templates folder - to load bootstrap, fonts, footer & content-blocks
- [x] Task5 Add index.html into templates folder
- [x] Task6 Add article_detail.html into templates folder
- [x]  Task7 in index.html, create a template to render the view
**Connect up URLs:**
- [x] Task8 Create urls.py file in the app (fp_blog) folder & add urlpatterns entry for "" (home)
- [x] Task9 Modify urls.py file in the project (financial-planner) folder, add urlpatterns entry for "", direct to include fp_blog.urls

**Comment by DeeMcCart** [comment]
23.10.23 Note - Re-used CI template files base.html, index.htm and post_detail (renameed to article_detail).html.
Copied across CI style.css & modified classnames to read 'article' rather than 'post'

**Comment by DeeMcCart** [comment]
Done 23.10.23 see screenprint below (just one article in database at present).  Still some work to do on tuning the site appearance in base.html and style.css but will come back to that later.

![agile-user-story-ability-to-see-list-of-articles](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/d2212c25-3552-43cb-aba8-dab97eaddb97)

**Comment by DeeMcCart** [comment]
Added some more articles so 7 published articles in total to check if pagination is working - yes, as per screenshots below:



![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/84fffb9e-0475-4dbe-b633-696a0dede0f1)

see second page here:



![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/99d02814-a0b8-4551-b358-2f98cd518007)

**Comment by DeeMcCart** [comment]
23.10.23 Also informally tested to ensure that the user only sees articles at 'published' status, not 'draft' status
