### ISSUE TITLE
User Story:  As a site user I can click on an article to see details

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#14]
EPIC:  **MVP**

As a **Site User** I can **click on an article to select it** so that **I can view article content/ detail**

### Assumptions:
Admin profile creates the posts
User can start from the list of published articles on the site homepage

### Acceptance Criteria
* User clicks on an particular article on the homepage list, and the article is shown on its own page/tab with full detail available to view.
 
### Tasks (Model - View - Templates)
**Model** : already done
**View** : 
- [x] Task1 In views.py, create class ArticleDetail(View)
**Templates**: 
- [x] Task2 Edit article_detail.html in templates folder
- [x] Task3 in index.html, create a template to render the view
**Connect up URLs**: 
- [x] Task4 Edit urls.py file in the app (fp_blog) folder & add urlpatterns entry for "'<slug:slug>" (article link)
- [x] Task5 Modify index.html anchor link for article detail to read <a href="{% url 'article_detail' article.slug %}

**Comment by DeeMcCart** [comment]
Done 24/10/23.  See example below.  Note that the url at the top is the article slug.  The user can return to the home page by either clicking Home (best practice) or using the back button.

![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/ad5dca61-fb76-4885-9929-f59b8c393712)

**Comment by DeeMcCart** [comment]
I would really like to have action items visible to the user on this details page!
