### ISSUE TITLE
User Story:  As site admin I can assign actions to articles so that users are prompted with follow-on action

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#15]
EPIC:  MVP

As a **site admin** I can **for a particular article, assign suggested actions (in a particular sequence)** so that **users are prompted with follow-up action(s)**

### Assumptions:
* Most Financial_Planner articles are advisory in nature and have 'natural' follow-on actions
* Suggesting follow-on actions to users prompts users to engage with the site content more deeply, and thereby promotes user learning (supporting the goal of increasing financial literacy)
* An article may have 0 or multiple actions
* Actions may need to be arranged in a particular sequence, when a particular action depends on a predecessor
* Not sure - are there some actions which could apply to multiple articles (perhaps consider this for a future release?)

### Acceptance Criteria
* Admin user can add suggested actions to an article 
* Display sequence of suggested actions can be amended by admin user

### Tasks

- [x] Task1 Check models.py to ensure the 'Actions' model is valid and includes slug as a FK
- [x] Task2 Amend views.py to ensure actions are retrieved under class ArticleDetail(View)
- [x] Task3 Amend article_detail.html to display the associated actions for a particular article
- [x] Task4 Create some associated actions for an article
- [x] Task5 Test it

**Comment by DeeMcCart** [comment]
24.10.23 
Task1 - Models already includes Actions model, this uses Article as FK (rather than slug) - seems to work OK so haven't changed this.   I had already created some dummy data for one of the artices.
Tasks 2-5 : Done - a very simple display format with a simulated fa selection/checkbox beside each action.  
This functionality will need to be added-to later on to make action items selectable and initiate a 'copy to user's profile' step ... however visibility of the actions is sufficient to complete this user story (MVP)....

DEVELOPMENT SITE:

![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/4daa1acd-092e-430b-bac7-453942fd855b)

DEPLOYED SITE:


![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/6468114f-f05a-4cc1-9af3-9ebe6755053d)
