### ISSUE TITLE
User Story:  As a site user I can register to create a personal profile so that I can personalise my site experience

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#16]
EPIC:  MVP

As a **site user** I can **register to create a personal profile** so that **I can personalise my site experience**

### Assumptions:
* For MVP the personal profile is pretty basic (but should include ability to like and bookmark articles)
* It is likely that the personal profile will expand in future releases
* SSO not yet required  (but would be nice-to-have for a future release)

### Acceptance Criteria
*  User has ability to register and create a personal profile with profile name, email address, basic details. 
* 

### Tasks

- [x] Task1 settings.py - set ACCOUNT_EMAIL_VERIFICATION to :NONE
- [x] Task2 pip3 install django-allauth & freeze requirements
- [x] Task3 (project-level) urls.py - add allauth urls
- [x] Task4 settings.py - update INSTALLED_APPS with 'allauth', 'allauth.account', 'allauth.socialaccount'
- [x] Task5 settings.py - add SITE_ID = 1 ; LOGIN_REDIRECT_URL = '/';
- [x] Task6 settings.py add allauth.account.middleware.AccountMiddleware
- [x] Task7 save and run migrations python3 manage.py migrate
- [x] Task8 base.html - update links for logout, signup, signin

**Comment by DeeMcCart** [comment]
Done 27.10.23 pretty much as per walkthrough.  Not sure whenter to use signup/signin/ signout or register/login/ logout.  Will check soe other websites to see what looks best (I kind of prefer al the S's in the first option).  Implementing these steps gives 3 new functional screens which look pretty basic, as per below:


![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/1422420c-9028-4e33-b6a6-95d663787a18)



![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/419e62c6-0bf0-48b6-94b3-a043bb4474a9)



![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/ee3dead8-5b29-451f-b837-b6d4e0334b70)
