### ISSUE TITLE
Task:  Extend allauth functionality and standardise templates to improve UX

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#17]
EPIC:  UX

This extends Issue #16 

### Assumptions:
* Allauth functionality is installed & operational

### Acceptance Criteria
* Registration screen provides meaningful messages and hints (including recommendation not to set username = email address as it is a 'public' field) and meaningful messaging re passwords
* If an invalid password is entered the error message is clearly identifiable and stands out on screen (to avoid user confusion)
* Registration/Signup, Login/Signin, SignOut, Password reset pages all similar appearance and feel/ functionality.

### Tasks

- [x] Task1 Check python version installed in workspace using ls ../.pip -modules/lib
- [x] Task2 Copy subdirectories recursively to create templates folders:  cp-r ../.pip-modules/lib/pythonX.Y/site-packages/allauth/templates/* ./templates
- [x] Task3 Verify that the templates folder now has account, mfa, opnd, socialacccount, tests subfolders.
- [x] Task4 Modify the standard Django template under login.html.  N.B. {% extends "base.html" %}.  Add in some standard bootstrap classes, and modiify the  h1 headings down to h3
- [x] Task5 Modify the signout page in a similar manner
- [x] Task6 Modify the Registration/Signup page in a similar manner
- [x] Task7 Modify the password reset page in a similar manner

**Comment by DeeMcCart** [comment]
Task1 Python **3.9** 
 Task2 cp-r ../.pip-modules/lib/python**3.9**/allauth/templates/site-packages ./templates

**Comment by DeeMcCart** [comment]
![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/8909e5e5-86c6-4a04-b166-a0e4b233adf9)



![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/21ca9f89-c508-4a7e-ad3c-741a8bdd1a8b)



![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/397be3ad-daf4-4150-9b90-f5baee70928b)



![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/7298094f-7857-4caa-8ba6-f5fd4309a4b1)

**Comment by DeeMcCart** [comment]
30/10/23 (Sprint 5 retrospective) this issue was worked on during sprint 5, and has met the acceptance criteria, so am marking closed. Will log the problems identified as bugs and investigate separately.
