### ISSUE TITLE
User Story:  User comments on articles

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#18]
EPIC:  MVP

As a **site user** I can **leave comments on a post** so that **I can add my useful experience to the advice given**
As a **site admin** I can **view/approve/delete user comments on a post** so that **I can moderate site content**

### Assumptions:
N/A

### Acceptance Criteria
* User/admin can add comments
* Newly added comments default to 'unapproved' status, and are visible only to the creator
* The creator sees a message to tell they have unapproved comment(s) against an article
* Unapproved comments are not shown (or counted) on the articles page 
* Admin can update comment status to approved
* Admin can delete comments (unapproved and approved) as required 

### Tasks 
- [x] Task1 Install crispy forms using pip3 instll django-crispy-forms==1.14.0
- [x] Task2 freeze requirements pip3 freeze --local>requirements.txt
- [x] Task3 settings.py INSTALLED_APPS=[..., 'cris py-forms', ...]
- [x] Task4 settings.py CRISPY_TEMPLATE_PACK="bootstrap4"
- [x] Task5 Setup new file forms.py
- [x] Task6 Modify views.py: return render
- [x] Task7 Modify article_detail.html to {% load crispy_forms_tags %}; add form structure
- [x] Task8 Modify views.py article_detail class:  add a post method
- [x] Task9 Modify post_detail.html

**Comment by DeeMcCart** [comment]
30.10.23 :  Done but issue with 'your comment is awaiting approval' even after approval - pick up tomorrow.  Note, had to add missing 'name' field into the models.py for comments and re-migrate, also had to update the admin.py as hadn't included comments in this first time around.

**Comment by DeeMcCart** [comment]
30/10/23 (Sprint 5 retrospective) this issue was worked on during sprint 5, so is largely completd. Keeping in Sprint5 and will double check the issue this morning and hopefully clear it off and closeout the issue as part of Sprint5

**Comment by DeeMcCart** [comment]
30/10/23 end of day - there is a small bug within comment processing.  The bug is that if user1 creates a comment which is awaiting approval, the screen will initially display 'your comment is awaiting approval' and user1 (correctly) cannot add a second comment.  
If user2 then creates a comment on the same article and gets the message 'your comment is awaiting approval', user2 then can't add additional comments (working correctly).
However if EITHER comment is approved then the 'your comment is awaiting approval' message disappears for ALL users.  This means that user1/user2 could then add more unapproved comments which pile up waiting for approval.
Raised as a bug under issue #25  Closing out this issue #18
