### ISSUE TITLE
User Story:  Ability to Like/Unlike an Article

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#19]
EPIC:  MVP

As a **site user** I can **like/unlike an article** so that **I provide feedback to other users about which articles are most useful**
As a **site user/Admin** I can **view the number of likes on each article** so I can **see which is the most popular or useful**

### Assumptions:
* Multiple users exist within the database

### Acceptance Criteria
* In article detail view, a user can click on a 'like' button associated with an article
* If the user is registered/logged in then the number of 'likes' associated with that article will increment
* If the user is not logged in, they will receive a warning message to tell them the action has no effect unless logged in
* If a user who has 'liked' an article clicks on the 'like' button a second time then the number of 'likes' associated with that article will decrement

### Tasks 
- [x] Task1 Modify views.py to add httpresponseredict etc and create class ArticleLike
- [x] Task2 Update template article_detail.html
- [x] Task3 Add URL path to urls.py

**Comment by DeeMcCart** [comment]
30/10/23 (Sprint 5 retrospective) this issue was scheduled for Sprint5 but not done.  Moving to Sprint 6.  Remains in 'to do' status as already been groomed, LOE SP estimates still valid. This should be close to top of priority list as needed for MVP, before moving on to any Release1 work.

**Comment by DeeMcCart** [comment]
Done 01/11/23 - Done & tested separate userids adding and removing likes.  One acceptance criterion not fully met - an unregistered user sees an onscreen message beside the 'like' button to tell them it cant be clicked unless they login, however would prefer if this message only appears if they attempt to click the button...

**Comment by DeeMcCart** [comment]
Review/test 01/11/23:
If the user is not logged in then they have an alert message telling them to login before they are allowed to like/unlike or make comments:


![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/66534d6f-7a07-4636-8cb8-06ce0424207d)

If they are logged in and they have not yet clicked on like, an icon with a heart outline displays:


![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/714aa9b7-d78c-4ca0-a189-34dd884ea7c3)

If they click on the like button then the number of likes increments and the button changes to a solid red heart button


![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/c59fde3c-3f3f-4561-a172-26bba8bfbe6f)

If they sign out and back in, the like button still shows the incremented value and a solid red heart for this user:


![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/f9059a25-6694-4293-bce3-43e0f4a8db53)

If they click on the like icon again then the number of likes decrements and the icon changes back to a heart outline:


![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/3ba72fd6-2cde-465d-9b55-b8cd43d54a93)
