### ISSUE TITLE
Task:  UX Research: Scope

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#2]
As a **UX designer** I can **understand scope of Financial-Planner** so that **I can address a market gap/ customer need**

### Assumptions

*  Scope will need to include MVP features and desirable features
*  Geographic & legal scope (Repubic of Ireland) decided

### Acceptance Criteria

*  MVP Features for a financial guidance website are included in proposed scope
*  Desirable features for a financial guidance website are identified
*  Features identified in UX strategy as desirable are included/ excluded

### Tasks

- [x] Decide site purpose
- [x] Decide what type of content will be included
- [x] What features must be included for MVP?
- [x] What features are desirable? (although possibly not MVP)

**Comment by DeeMcCart** [comment]
This issue drifted along for several weeks being kicked around while potential users (informal focus group)/ other developers were consulted.   Finally put to bed 18/10/23.....
* site purpose has to be more than just re-presenting the information available on existing sites (consumer protection site ccpc, citizens advice, revenue, pensionsauthority.ie)
* as the existing sites tend to be largely text-based then the preferred delivery mode is mixed-media (infograms, pictures, ideally short video clips)
* there is very little financial literacy training available online for adults, and what is presented is often biased towards mathematical calculations (e.g. abiliity to calculate compound interest), it may make more sense to focus on the CONCEPT of compounding rather than make someone feel inadequate becuase their mathematical understanding is not strong.
* existing information sites dont tend to use Persona-based navigation this is in an opportunity

**Comment by DeeMcCart** [comment]
1. Site Purpose:  
1.1 To provide access to authoritative financial information and guidance
1.2 To offer persona/role-based navigation to topics of interest ('I want to: buy a house / start a pension....')
1.3 To offer the user an opportunity to interact with topics of interest through bookmarking, liking, copying to a personal folder, making personal notes about a topic
1.4 To offer an alternative to purely text-based navigation of financial guidance/information

2. What type of content will be included:
2.1 links to authoritative articles from trustworthy sites
2.2 Persona-based navigation
2.3 Information presented in varying modes including text, infographics, pictorial, video.
2.4 Interactive capabilities through creation of personal action items, bookmarking, liking
2.5 (Ideally some calculators and games)

3. Features to be included for MVP:
3.1 Django-based articles database allowing admin CRUD facilities for articles
3.2 Django-based themes/categories functionality, manageable by admin with the ability to link articles to a particular theme
3.3 Ability to like and bookmark articles
3.4 User registrations/ signon capabilities

4. Desirable Features
4.1 Ability to associate suggested action items with articles  
4.2 Ability to 'copy' suggested actions to a user's personal action list
4.3 Ability for user to maintain (CRUD) their personal action list
4.4 Multimedia presentation of information e.g. infographics
