### ISSUE TITLE
User Story:  Update personal action list

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#21]
EPIC:  <Peronal Financial Planner>

As a **registered user** I can **update actions on my personal Financial Planner** so that **I can track my progress on actions I'm committed to following up**

### Assumptions:
* This satisfies the Update - Delete requirements for personal Financial Planner
* It is enough to have one field per action of actions taken and observations (rather than having a one to many relationship between planned actions and actions-taken/ observations)
* Pre-requisite issue #32 has been completed

### Acceptance Criteria
* Registered user can see their Personal FP actions 
* Personal FP actions can be updated with actions taken (200 chars) and observations (200 chars)
* Actions can be selected for deletion, and can be deleted subject to a confirmation message ('you are about to delete X actions, are you sure you want to continue')

### Tasks

- [x] Task1 Add select/edit form to user profile page
- [x] Task2 setup forms, views, urls, html for CRUD
- [x] Task3 Apply basic styling to delete-confirm screen
- [x] Task4 Test each of the CRUD functions
- [x] Task5 Note further actions to improve appearance/functionality

**Comment by DeeMcCart** [comment]
30/10/23 Sprint 6 Planning - added to sprint, still in backlog as tasks still to be identified (12 SPs identified and acceptance criteria drafted)

**Comment by DeeMcCart** [comment]
Done - appearance is pretty basic but its fine....

![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/70547308-1938-46bc-bfb8-55b4ca57bf34)

**Comment by DeeMcCart** [comment]
**Delete:  Select issue20 for deletion:**


![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/bca160de-d682-41b9-81cd-fb25cba0bab9)




** Delete confirmation screen appears, select 'go back'**

![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/b22ae89d-40d3-449c-aec8-ddd40aa3e042)



**Action 20 is still on the list.  Select it again for deletion**

![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/d51ce3e8-5f48-4044-95e7-6a3a11d18193)


**Delete confirmation screen appears, select 'Confirm'**



![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/968e7573-5a56-480d-a118-d5a33e65ef80)




**Action 20 has now been deleted from the list.**

![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/c2467d48-3eb4-4827-8530-c154163dd468)
