### ISSUE TITLE
User Story:  Bookmarks/ Favourites

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#22]
EPIC:  <Personal Financial Planner>

As a **registered user** I can **mark articles of interest** so that **I can see a set of linked articles within my profile and can access them at a time that suits me without needing to return to search the main article page**

### Assumptions:
Issue #29 has been completed
Issue #32 has been completed.

### Acceptance Criteria
* When browsing articles, a registered/returning user can bookmark an article
* On opening their user profile, a registered/returning user can see a list of the articles bookmarked, sorted by date
* From the user profile screen, the user can remove bookmarks no longer of interest

### Tasks

- [x] Task1 Add ability to bookmark an article - from index.html page and from article_detail.html page
- [x] Task2 Add bookmark count for article - on index page and on article_detail page
- [x] Task3 Add bookmark count per user to user profile page
- [ ] Task4 Add link to Bookmarks form on user profile page
- [ ] Task5 Ability to select individual bookmarks and delete them (one at a time or several together)

**Comment by DeeMcCart** [comment]
06/11/23 Returned to backlog as not completed within Sprint6
