### ISSUE TITLE
Task:  Create additional database structures to support Personalised Financial Planner

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#29]
EPIC:  <Personal Financial Planner>
**Release 1: Personal Financial Planner**
As a **registered user** I can **create and track personal Financial Planner actions** so that **I improve control over my finances**

### Assumptions:
* MVP Financial_Planner functionality (articles, article actions, comments, likes) has been delivered and is functioning correctly

### Acceptance Criteria
* Registered User can be associated with the additional fields profile_pic, year_of_birth, bookmarked_articles, associated_actions 

### Tasks
- [x] Task1 Create new app fp_personal for Personal Financial Planner
- [x] Task2 Update data design charts (LucidChart) to show how individual User, their associated User Actions, and their Favourite articles will be structured
- [x] Task 3 Create data model for User in models.py
- [x] Task2  Create data model for User_Actions in models.py
- [x] Task3 Work out how to represent favourite/ bookmarks

**Comment by DeeMcCart** [comment]
04/11/23 
Created new app fp_personal for personal financial planner.
Provisionally created data models for UserProfile and UserActions in models.py.  
Need to review these tomorrow to check logic is correct before building migrations.  Also need data model for user's favourite articles.

**Comment by DeeMcCart** [comment]
3 datasets now visible under fp_personal on the admin console:
![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/0d1d5f40-5459-429a-b12a-977fab33c037)

It is possible to add/maintain personal user actions from the admin console:


![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/e09804a2-4929-4bd6-9516-3e2fb929bdd2)

It is possible to add/maintain user profiles from the admin console:


![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/89ec9969-a4a2-4a41-a4ff-49a0319fb668)

It is possible to add/maintain user favourites from the admin console:

![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/17d4db6b-90f9-41e4-8cb6-3ae85f8f2539)

**Comment by DeeMcCart** [comment]
Updated LucidChart database diagrams:

![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/a094edb0-2ab5-4531-9300-60a47a5eb5e3)
