### ISSUE TITLE
Task:  UX Research: Strategy

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#3]
As a **UX designer** I can **explore existing financial literacy (competitor) websites and offerings** so that **I can understand and list desirable featres for a financial info/education website**

### Assumptions

*  Only interested in sites specific to the legal territory of Republic of Ireland, as resources/policies/laws vary across geopolitical boundaries, e.g. the rules for Northern Ireland are quite different, as are those for the UK
*  There are a lot of websites out there
*  Not all are authoritive sources, so its important to recognise which may have bias and which are most trustworthy
*  There is a stated gap in adult financial literacy in Ireland (Department of finance, August 2023)

### Acceptance Criteria

*  Existing sites providing financial education/ knowledge resources/ impartial guidance are listed
*  Key features of each site are listed
*  MVP Features for a financial guidane website are identified
*  Desirable features for a financial guidance website are identified

### Tasks

- [x] Build a catalogue of digitally accessible (website/ download) financial literacy resources for Republic of Ireland
- [x] Identify key features for each item
- [x] Identify gaps or drawbacks for each item
- [x] Propose authoritative resources which can be used to provide content
- [x] Propose MVP Features for Financial_Planner site
- [x] Propose desirable features for Financial_Planner site
- [x] Identify target audience for Financial_Planner site

**Comment by DeeMcCart** [comment]
[https://docs.google.com/spreadsheets/d/1tbfAYpQ9rYQEJTYCZf6XIhw-CiIIDiPSMWqqE87byw0/edit#gid=0](Google sheets research document)

**Comment by DeeMcCart** [comment]
This task was largely done during September but formally closed off 19/10/23..... ref link to Google sheets spreadsheet above.  

### Firstly I tried to seek out internet-accessible resources for Financial Literacy education in Ireland.  
Online resources are largely non-existent, with the exception of 'Money Matters' and 'Me and My Money' secondary school (Junior Cert) resources, 'Money Counts' secondary school (senior cycle) resources, with downloadable lesson plans for in-person teaching.
No resources were found via Google search for standardised curricula or training for Irish adults outside the school system, although mention was found of adult nightclasses teaching household budgeting.
-- so definitely a large opportunity for standardised Financial Literacy training for adults (but beyond the scope of this project) --

### Secondly, I tried to find authoritative resources and websites for financial information gathering and decision making in ireland.  
I discovered several individually useful sites e.g. citizensadvice.ie, ccpc.ie, revenue.ie, pensionsauthority.ie.  Hwever, while these were very information-rich, the information is presented as large text blocks with little opportuity for the user to interact with the content, e.g. few tools or bookmarking capabilities.

**Comment by DeeMcCart** [comment]
### MVP Features for Financial_Planner site:
* information rich
* information mush b e accessible
* site ust be responsive

###  Propose desirable features for Financial_Planner site
Alternative to pure text-based dislay

 ### Identify target audience for Financial_Planner site
Adults (over 18s) outside the secondary school system, who are subject tot he laws and financial rgimes of Ireland and who wish to improve their knowledge of financial topics
