### ISSUE TITLE
Task:  Design & Create database structures for Lifestage info display (Release2)

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#30]
EPIC:  <Personal Financial Planner>

As a **role** I can **capability** so that **received benefit**
**Release 2: Themes/ Lifestage Planner**

### Assumptions:
* MVP is up & running

### Acceptance Criteria
* Additional page where user can access article metadata via a 'life stage' theme, e.g. buying a house 
* Infograms (is that the right word?) showing sequence of steps to perform a particular need, and highlighting the relevant articles, are offered to the user who wants to perform a particular multi-stage activity

### Tasks
- [x] Task1 Install Djago-Taggit to extend the article view
- [x] Task2 Create data model for Themes in models.py (ie extend Article model to include Taggit tag attribute)
- [x] Task3 Confirm deployment still working post Taggit install (verson 4+ Python rather than 3+)
- [x] Task4 Add tags to articles via the admin portal (tag structure L:xxxxx for lifestyle tag, T:yyyyyy for article tag, comma separated
- [x] Task5 Add search form to index page
- [x] Task6 Rewrite retreival of index page contents using function- rather than class-based view
- [x] Task7 Reapply pagination (and try 4 rather than 8 articles per screen) 
- [ ] Task8 Install Extend views.py to include tag fields + add capability for tag based search
- [ ] Task6 Extend modailty of index page to search by lifestye stages

**Comment by DeeMcCart** [comment]
21/11/23 DONE for index page search field - however am not convinced with the results it is returning.... might look again at tag fields
