### ISSUE TITLE
User Story:  standardise messge displays

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#31]
EPIC:  **UX** 

User Story:  As a **site admin** I can **standardise messge displays** so that **the user experience is smooth and MVP is achieved**

### Assumptions:
* MVP functionality is largely in place
* Messages are set to display in certain circumstances
* 
### Acceptance Criteria
* Message display is clear and consistent for users
* Messages display at appropriate points

### Tasks

- [x] Task1 settings.py ensure messsages included in INSTALLED_APPS
- [x] Task2 settings.py Assign message classes -> bootstrap classes by assigning tags to each
- [x] Task3 base.html - Add message display
- [x] Task4 base.html - script file to control how long messages remain on-screen

**Comment by DeeMcCart** [comment]
02.11.23 Implemented as per walkthrough - tested just for simple messages at sign-in and sign-out (see test screenprints below).  However I don't fully understand mesaging, for example if the user enters an inappropriate password at the time of registering they just get on-screen message which is not great because they aren't highlighted and don't stand out.

What I've implemented is OK for now, but I'd like to improve this during the remainder of project time.  Moving to status DONE but may raise a separate user story/task later to improve messsaging UX.

**Comment by DeeMcCart** [comment]
Confirmation of sign-in


![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/ccf20100-2b83-4e4a-9457-1caa4c2df113)



Confirmation of sign-out



![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/cc40c7bd-b6b5-495d-9dc7-1d9a49f451de)



However, password errors at registration just show as on-screen messages, still in balck & white so are very frustrating as these really need to be messages as well:


![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/c05221d9-8117-4dc8-8270-303fbc7a3dbf)
