### ISSUE TITLE
User Story:  Returning user, create and update personal profile page UserProfile and Bookmarks

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#34]
/EPIC:  Personal Financial Plan

As a **returning user** I can **maintain my personal profile** so that **I can personalise my experience and track the articles and actions I wish to pursue**

### Assumptions:
This is a split of issue#32 which was partially completed in sprint #7.  While #32 put the basic structure in place some of the functionality such as the ability to create and maintain a user profile, and the ability to view and edit bookmarks for this user, wasn't delivered, so this issue has been created for the next sprint.

### Acceptance Criteria
* User can add/maintain a personal user profile (CRUD user profile)
* User can see list of & maintain bookmarks for articles of interest (CRUD bookmarks)

### Tasks

- [x] Task1 User profile is currently read-only (maintained via admin backend).  Allow user to maintain own profile ie to change profile photo, year of birth, exact age
- [x] Task2 User registration (creating an AllAuth 'User' to allow likes/comments/bookmarks) is currently separate to User Profile (personalising, adding profile photo, year of birth, personal actions)... review and determine if these should somehow be combined into one page?
- [x] Task3 Total # of likes, bookmarks, favourites, action items is currently shown on user profile page.  Provide a button link from each icon to see the underlying data.  
- [x] Task4 Ability to select individual bookmarks and delete them (one at a time or several together)
- [x] Task5 (Optional) Provide a page/portal to update/delete likes to articles from the user profile page

**Comment by DeeMcCart** [comment]
**SPRINT 7 REVIEW 13/11/23:**
Created this issue to cover outstanding items from issue #32 and issue #22 within sprint7.

**Comment by DeeMcCart** [comment]
13/11/23 - Task3, task4 - done - note that delete is one per record and the user gets a confirm delete page..... note that these have been achieved using function-based rather than class-based views so may need to be revisited.
