### ISSUE TITLE
User Story:  Feedback

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#37]
EPIC:  **Feedback Form**

As **site owner** I want to provide an **opportunity for the user to provide feedback**, to **gather reported issues and suggested improvements** for the Financial Planner site

### Acceptance Criteria

* Simple 'about' page 
* With opportunity for the user to create feedback which gets logged to a database

### Tasks

- [x] Task1 Create model, @admin, (run migrations) view, html template page
- [x] Task2 Add text to 'About' page
- [ ] Task3 Setup feedback in views to process get
- [ ] Task4 Setup feedback form in About page

**Comment by DeeMcCart** [comment]
Models etc created 18/11/22
