### ISSUE TITLE
User Story:  Update Readme

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#38]
EPIC:  <epic>

As a **system designer** I can **clearly explain site purpose, features and design** so that **the intention and delivered site can be understood by an assessor**

### Assumptions:
* The site is pretty much in place, just needing some final tweaks (!!)

### Acceptance Criteria

* Readme contains all necessary sections
* 

### Tasks

- [x] Task1 User story x reference to features
- [x] Task2 Features section
- [x] Task3 Validataion docs
- [x] Task4 Deployments Section

**Comment by DeeMcCart** [comment]
14/11/23 1 hour on wireframe updates and double checking user stories
