### ISSUE TITLE
User Story:  System Testing and Problem Tracking - Sprint 8

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#39]
EPIC:  VALIDATION

FTU_07 As a first-time user I expect links and functions that work as expected so I can use the site confidently

** Testing and issue tracking **

### Assumptions:
* Most components of solution in place
* Ongoing activity during the final 2 sprints before delivery
* 
### Acceptance Criteria
*  Issue tracking spreadsheet is maintained 
* 

### Tasks
- [x] Task1 Log problems on ongoing basis into tracking spreadsheet
- [x] Task2 If issue is large, consider creating 'bug' issue within github project
- [x] Task3 Track fixes initially in spreadsheet
- [x] Task4 Assign daily time to working on issues

**Comment by DeeMcCart** [comment]
Ongoing - sprint 8 - issue log up to 53 items: 24 open 29 closed.  Creating this isssue again for Sprint 9.
