### ISSUE TITLE
User Story: Validation - Sprint 8

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#42]
EPIC:  Validation

SO_06 As **site owner** I want to **provide a website, which meets current programming, performance and accessibility standards (html, css, javascript, responsive, accessibility, performance)** so that **users can enjoy a high-standard experience**

### Assumptions:
System has reached a stable point (note that some of these valiation tests may need to be repeated prior to handover)

### Acceptance Criteria

* All validation tests must be completed
* All validaton tests must pass, unless a reasonable explanation can be provided for failure

### Tasks

- [x] Task1 W3C validation of each html file (needs to be based on rendered, rather than source, html, as source includes non-html control codes)... using checker at [https://validator.w3.org/nu/#file](https://validator.w3.org/nu/#file)
- [ ] Task2 Accessibility checking of each customized HTML file using [https://wave.webaim.org/report#/](https://wave.webaim.org/report#/)
- [ ] Task3 CSS testing of style.css
- [ ] Task4 Lighthouse testing of overall site in Chrome
- [x] Task5 Python PEP8 testing (all altered py files) using [CI's PEP8 validator](https://pep8ci.herokuapp.com/#)
- [x] Task6 User Testing and feedback - round1 19/11/23

**Comment by DeeMcCart** [comment]
18/11/23 W3C validation done for index, my_planner, my_action html pages... more to follow
