### ISSUE TITLE
User Story:  UX (navigation and look-and-feel) consistent within financial_planner site - Sprint9

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#45]
EPIC:  UX

 SO04 As **site owner** I want to **provide straightforward, intuitive, consistent website navigation** so that users can easily retrieve financial information/guidance which is relevant to them

### Assumptions:
Site has been developed with deliverable functionality in place
Look and feel is currently inconsistent or inadequate on site pages

### Acceptance Criteria

* Use graphical navigation where possible,including when accessing text-based informataion
* Consistent appearance of forms
* Consistent navigation

### Tasks
- [ ] Task1 Confirm/cancel button needed when adding user action (ie can go backward if needed)
- [ ] Task2 When a user takes like/unlike bookmark/unbookmark from the index page, the article detail page is displayed - should refresh and redisplay the index page instead
- [x] Task3 Think about page layout on MyPlanner page, when this is displayed on tableet (portrait) there's too much content 
- [ ] Task4 Alter comment display appearance below article
- [x] Task5 404 page
- [x] Task6 Deploy to Heroku Mon 20/11 for user testing
- [x] Task7 Deploy to Heroku Tues 21/11 for user testing
- [x] Task 8 Deploy to Heroku Weds 22/11 for user testing
- [ ] Task9 Favicon in Heroku
- [ ] Task10 Email for password reset on Heroku (error 500)
- [x] Task11 Show/hide buttons for actions/comments on article detail

**Comment by DeeMcCart** [comment]
20/11/23: Task 3 DONE - added buttons to show/hide personal tasks(actions), reading list (bookmarsks), comments

**Comment by DeeMcCart** [comment]
extended the article model to rach out to actions:  actions = models.ManyToManyField(Action, related_name='article_actions', blank=True)???
