### ISSUE TITLE
User Story:  Issue tracking and problem solving - Sprint 9

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#46]
EPIC:  VALIDATION

FTU_07 As a first-time user I expect links and functions that work as expected so I can use the site confidently

** Testing and issue tracking **

### Assumptions:
* Most components of solution in place
* Ongoing activity during the final 2 sprints before delivery
* 
### Acceptance Criteria
*  Issue tracking spreadsheet is maintained 
* 

### Tasks
- [x] Task1 Log problems on ongoing basis into tracking spreadsheet
- [x] Task2 If issue is large, consider creating 'bug' issue within github project
- [x] Task3 Track fixes initially in spreadsheet
- [x] Task4 Assign daily time to working on issues

**Comment by DeeMcCart** [comment]
Done.  Project submitted, although there were still some open issues.  

![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/e00cda31-bddb-40b4-b0ba-d5b2ac00f244)

**Comment by DeeMcCart** [comment]
8 issue log items have been identified as FUTURE ad may be considered for the nxt developent cycle:



![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/89c2c057-2b4a-468d-bb65-85f14276bc76)

**Comment by DeeMcCart** [comment]
An additional 55 issues from the issuelog have been closed. Generally this is because an underlying problem has been fixed, or sometimes an acceptable workaround is found.

![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/a19433ac-42b1-47e2-8e3b-09f0678802c0)
