### ISSUE TITLE
UX Improvements (FUTURE) 

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#49]
EPIC:  UX

SO04 As **site owner** I want to **provide straightforward, intuitive, consistent website navigation** so that users can easily retrieve financial information/guidance which is relevant to them

### Assumptions:
Initial project is deployed/ submitted and some time is given to gather user feedback
The list below are **possible** worthy tasks from the developers perspective and based on initial testing & user feedback
These should be groomed before determining if each should remain as a requirement for the next release
This is a follow-on from task #45 which was closed with the submitted project.

### Acceptance Criteria
* Just trying to get a nice smooth running easy to use system where users can clearly see the flow and understand the processes
* Use graphical navigation where possible,including when accessing text-based informataion
* Consistent navigation
 
### Tasks
- [ ] Task1 Confirm/cancel button needed when adding user action (ie can go backward if needed)
- [ ] Task2 When a user takes like/unlike bookmark/unbookmark from the index page, the article detail page is displayed - should refresh and redisplay the index page instead
- [ ] Task3 Alter response/comment display appearance below article
- [ ] Task4 Favicon in Heroku
- [ ] Task5 Email for password reset on Heroku (error 500)
- [ ] Task6 'Share' icon on article
