### ISSUE TITLE
Task: UX Design:  Skeleton - data models

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#5]
EPIC:  UX

As a developer I want to correctly represent the real-world model so that I can deliver a site that meets user needs

### Acceptance Criteria
* Data Modls created
* Data Models reflect MVP requuirements
* * Data Models allow for future development
* 
### Tasks
- [x] Design Data Model for Articles
- [x] Design Data Models for Themes
- [x] Design Data Model for User Action List
- [x]  Document using an appropriat modelling tool

**Comment by DeeMcCart** [comment]
Created ERD using LucidChart 22/10/23.  This is not perfect but it is a first pass and maybe enough to work with for now.....

![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/f1bc8724-3bb4-4041-8907-f26519a53bc9)
