### ISSUE TITLE
Task: UX Design: Surface - wireframes

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#6]
As a **UX designer** I can **create wireframes for proposed Financial-Planner website** so that **I can show how the features will hang together**

### Assumptions

*  Design will need to include MVP features and desirable features

### Acceptance Criteria

*  Site structure/ navigation is identified
*  MVP Features for a financial guidance website are included in proposed design
*  Desirable features for a financial guidance website are identified
*  Wireframes produced in Balsamiq (or similar)

### Tasks

- [x] Identify site hierarchy from user perspective
- [x] Map out site hierarchy/structure from admin perspective
- [x] Add wireframe for each proposed page for MVP
- [x] Add navigation to desirable features for Financial_Planner site
- [x] Add comments/callouts as required to explain proposed website functionality

**Comment by DeeMcCart** [comment]
Balsamiq wireframes created 18/10/23 as follows:
** User perspective** of flow (not signed in/ signed in) to include - 
* Themes, 
* articles & action points, 
* MyPlanner, 
* About/Feedback, 
* Signin/Signout

**Admin perspective** of flow (must be signed in) to include - 
CRUD articles
CRUD themes
CRUD user profiles



![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/11018d5b-3a36-4d7b-98f7-bead23da4e76)
![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/3e58bfc6-fe45-4ad0-9bd9-f3bd216887dd)
![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/7a4d570a-9dec-44d5-9f23-c136c8d17040)
![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/ff5292b2-a808-4940-b873-fb6d51bb59ab)
![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/9693fb5a-652d-4bb2-a0cc-11da4b734d30)
![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/7af782c7-96c5-41cb-a4f2-803d27cd1f0c)
![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/57e18a93-4bb2-4a8d-8aa5-884fa774b94e)
