### ISSUE TITLE
Document Agile structures in READme

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#8]
EPIC:  DOCS

As a assesor I can see how GitHub features have been used to represent Agile so that I can be confident that it has been appropriately used

EPIC:  DOCS

Create initial Readme structure including Agile methodology and UX sections

### Assumptions:
Will be using Agile methodology and its setup will need to be explained in detail within the Readme
UX Sections can be partially completed e.g. scope, more detail can be added later

### Acceptance Criteria
* Agile - Project Setup is described
* Agile - Issue Template is described
* Agile - MoSCoW Prioritisation and representation using labels is described
* Agile - Milestone hierarchy is described
* Agile - EPICs approach is described 
* Agile - Iteration approach (sprints) is described
* Agile - spreadsheet view is described
* Agile - describe usage of story points
* Agile - Kanban board (and categories) is described
* Agile - leave a section for 'In practice what happened was...'
* Remaining sections added as placeholders within the READme

### Tasks
- [x] Describe Project Setup 
- [x] Describe Issue Template 
- [x] Describe Planned Use of MoSCow Prioritisation and representation
- [x] Describe Milestones approach
- [x] Describe EPICs approach
- [x] Describe Iteration approach (sprints)
- [x] Describe use of project-spreadsheet view
- [x] Describe planned usage of story points
- [x] Describe planned usage of Kanban board (and categories)
- [x] Populate an 'In reality' section
- [x] Add remaining placeholder sections to readme

**Comment by DeeMcCart** [comment]
25.10.23 Done in sprint 5 (earlier than planned).  Although I had setup the project structures I found myself delaying when it came to documenting them, and had moved this issue from one sprint to the next.  Finally done Weds 25/10/23, will still need to revisit the readme file closer to end of project, however now have a reasonable attempt at Agile documentation with associated screenprints (enough for MVP)

**Comment by DeeMcCart** [comment]
![agile-issues-kanban-view-sp-epic-num-issues-per-col](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/b966161c-015d-4624-b22c-993d772b66c8)

**Comment by DeeMcCart** [comment]
Weds 25/10/23 Moved to Done, closing issue now
