### ISSUE TITLE
Task:  Setup Agile Structures in Github Project

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#9]
EPIC:  Agile

Setup required parameters in GitHub to appropriately represent Agile methodology

### Assumptions:
Will be using Agile methodology which will be tracked within GitHub

### Acceptance Criteria
* Agile - Project is Setup 
* Agile - Issue Template is setup
* Agile - MoSCoW Prioritisation and representation using labels is setup
* Agile - Milestone hierarchy is setup
* Agile - EPICs approach is setup
* Agile - Iteration approach (sprints) is setup
* Agile - spreadsheet view is setup
* Agile - usage of story points is enabled
* Agile - Kanban board (and categories) is setup

### Tasks
- [x] setup Project 
- [ ] setup Issue Template 
- [ ] setup labels for MoSCow Prioritisation
- [ ] setup Milestones (initially MVP and Final_Version)
- [ ] setup EPICs
- [ ] setup iterations/(sprints)
- [ ] setup project-spreadsheet view with additional fields (e.g. EPICS, SPs) and narrow columns to make entire width visible
- [ ] setup Kanban board (and categories)

**Comment by DeeMcCart** [comment]
Setup mid-September and tweaked (custom fields) week of 09/10/23:

![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/6dac58f2-793a-4f93-8ef7-d5adcc2d1a65)



![Image](https://github.com/DeeMcCart/CI_PP4_Financial_Planner/assets/126502176/5ae60ed8-e44d-4348-b334-39a35318728c)
